<h2>Users</h2>
<?php echo $this->ToolsForm;?>
<table class='spreadsheet' cellspacing='0'>
<tr>
<th>ID</th>
<th>Name</th>
<th>Slug</th>
<?php foreach($this->langs as $lang){echo "<th>".$lang['slug']."</th>"; }?>
</tr>
<tr>
<?php echo $this->partialLoop('admin/table-row.phtml', $this->paginator); ?>

</table>
<?php echo $this->paginationControl($this->paginator,'Sliding','/pagination-control.phtml'); ?>
