<h2>Users</h2>
<?php echo $this->ToolsForm;?>
<table class='spreadsheet' cellspacing='0'>
<tr>
<th><?php echo $this->translate('ID')?></th>
<th><?php echo $this->translate('Title')?></th>
<th><?php echo $this->translate('Slug')?></th>
<?php foreach($this->langs as $lang){echo "<th>".$lang['slug']."</th>"; }?>
</tr>
<tr>
<?php echo $this->partialLoop('admin/table-row.phtml', $this->paginator); ?>

</table>
<?php echo $this->paginationControl($this->paginator,'Sliding','/pagination-control.phtml'); ?>
