<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title><?php $title=(string)$this->pageTitle; echo $this->translate($title);?></title>
		<link rel="stylesheet" type="text/css" href="/css/reset.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/text.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/grid.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/admin-layout.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/admin-nav.css" media="screen" />
		<!--[if IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" /><![endif]-->
		<!--[if IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen" /><![endif]-->
        <link rel="stylesheet" href="/js/themes/base/jquery.ui.all.css">
	<script src="/js/jquery-1.7.1.js"></script>
	<script src="/js/ui/jquery.ui.core.js"></script>
	<script src="/js/ui/jquery.ui.widget.js"></script>
	<script src="/js/ui/jquery.ui.tabs.js"></script>

	<script src="/js/ui/jquery.ui.button.js"></script>
    <script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
	<script src="/js/ckeditor/sample.js" type="text/javascript"></script>
	
	<script>
	$(function() {
	   	$( "input:submit" ).button();
        
        $("span.edit").addClass("ui-icon ui-icon-pencil ui-state-default ui-corner-all");
        $("span.delete").addClass("ui-icon ui-icon-closethick ui-state-default ui-corner-all");
		$( "#tabs" ).tabs();
        $("span.view").addClass("ui-icon ui-icon-zoomin ui-state-default ui-corner-all");
            $("span.add").addClass("ui-icon ui-icon-plus ui-state-default ui-corner-all");   
$( ".edit" ).button( "option", "icons", {primary:'ui-icon-gear',secondary:'ui-icon-triangle-1-s'} );
	});

	</script>
	</head>
	<body>
		<div class="container_16">
			<div class="grid_16" id="top-breadcrumb">
				
					<a href="/admin/"><?php echo $this->translate('cpanel');?></a>
			
			</div>
			<div class="clear"></div>
			<div class="grid_16">
                         <ul class="nav main">
                             <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'admin')) ?>"><?php echo $this->translate('index') ?></a></li>
				<li><a href="<?php echo $this->url(array('module'=>'user','controller'=>'admin')) ?>"><?php echo $this->translate('users') ?></a>
                                    <ul>
<li><a href="<?php echo $this->url(array('module'=>'user','controller'=>'admin','action'=>'add')) ?>"><?php echo $this->translate('adduser') ?></a></li>
<li><a href="<?php echo $this->url(array('module'=>'user','controller'=>'admin','action'=>'index')) ?>"><?php echo $this->translate('users') ?></a></li>
                                        
                                        
                                    </ul>
                                
                                </li>
                             <li><a href="<?php echo $this->url(array('module'=>'content','controller'=>'admin')) ?>"><?php echo $this->translate('content') ?></a>
                                    <ul>
<li><a href="<?php echo $this->url(array('module'=>'content','controller'=>'admin','action'=>'add')) ?>"><?php echo $this->translate('addcontent') ?></a></li>
<li><a href="<?php echo $this->url(array('module'=>'content','controller'=>'admin','action'=>'index')) ?>"><?php echo $this->translate('posts') ?></a></li>

<li><a href="<?php echo $this->url(array('module'=>'content','controller'=>'admin','action'=>'addcategory')) ?>"><?php echo $this->translate('addcategory') ?></a></li>
<li><a href="<?php echo $this->url(array('module'=>'content','controller'=>'admin','action'=>'categories')) ?>"><?php echo $this->translate('categories') ?></a></li>
                                        
                                    </ul>
                                </li>
                             
				</ul>
			</div>
			<div class="clear"></div>
			<div class="grid_16">
			<?php
if($this->flashmsg){echo $this->flashmsg;}
?>

				<?php     echo $this->layout()->content;?>
			</div>
			<div class="clear"></div>
			
			<div class="grid_16" id="site_info">
				<div class="box">
					<p>Fluid 960 Grid System, created by <a href="http://www.domain7.com/WhoWeAre/StephenBau.html">Stephen Bau</a>, based on the <a href="http://960.gs/">960 Grid System</a> by <a href="http://sonspring.com/journal/960-grid-system">Nathan Smith</a>. Released under the 
		<a href="../../../licenses/GPL_license.txt">GPL</a> / <a href="../../../licenses/MIT_license.txt">MIT</a> <a href="../../../README.txt">Licenses</a>.</p>
				</div>
			</div>
			<div class="clear"></div>
		</div>
            <script type="text/javascript">
			//<![CDATA[

				CKEDITOR.replace( 'editor',
					{
						skin : 'kama',
                                                height:"291", width:"700"
					});

			//]]>
			</script>
	</body>
</html>