<h2>Users</h2>
<?php echo $this->ToolsForm;?>
<table class='spreadsheet' cellspacing='0'>
<tr>
<th><?php echo $this->translate('Title')?></th>
<th><?php echo $this->translate('Username')?></th>
<th><?php echo $this->translate('Email')?></th>
<th><?php echo $this->translate('Status')?></th>
<th><?php echo $this->translate('View')?></th>
<th><?php echo $this->translate('Edit')?></th>
<th><?php echo $this->translate('Delete')?></th>
</tr>
<tr>
<?php echo $this->partialLoop('admin/table-row.phtml', $this->paginator); ?>

</table>
<?php echo $this->paginationControl($this->paginator,'Sliding','/pagination-control.phtml'); ?>
