<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title><?php $title = (string) $this->pageTitle;
echo $this->translate($title);
?></title>
        <link rel="stylesheet" type="text/css" href="/css/reset.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="/css/text.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="/css/grid.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="/css/layout.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="/css/nav.css" media="screen" />
        <!--[if IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" /><![endif]-->
        <!--[if IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen" /><![endif]-->
        <link rel="stylesheet" href="/js/themes/base/jquery.ui.all.css">
            <script src="/js/jquery-1.7.1.js"></script>
            <script src="/js/ui/jquery.ui.core.js"></script>
            <script src="/js/ui/jquery.ui.widget.js"></script>
            <script src="/js/ui/jquery.ui.tabs.js"></script>

            <script src="/js/ui/jquery.ui.button.js"></script>

            <script>
                $(function() {
                    $( "input:submit" ).button();
        
                    $("span.edit").addClass("ui-icon ui-icon-pencil ui-state-default ui-corner-all");
                    $("span.delete").addClass("ui-icon ui-icon-closethick ui-state-default ui-corner-all");
        
                    $( "#tabs" ).tabs();
        

                    $( ".edit" ).button( "option", "icons", {primary:'ui-icon-gear',secondary:'ui-icon-triangle-1-s'} );
                });

            </script>
    </head>
    <body>
        <div class="container_16">
            <div class="grid_16">
                <h1 id="branding">
                    <a href="/"><?php echo $this->translate('Home'); ?></a>
                </h1>
            </div>
            <div class="clear"></div>
            <div class="grid_16">
                <ul class="nav main">

                    <?php
                    foreach ($this->menu as $k => $v) {
                        $v = $this->url($v);
                        echo "<li><a href='$v'>$k</a></li>";
                    }
                    echo "</ul>";
                    ?>

                </ul>
            </div>
            <div class="clear"></div>
            <div class="grid_16">
</body>
                <div id='searchForm'>
                    <h2>Search Site</h2>
                    <?php
                    $searchForm = new Form_Content_Search();
                    $searchForm->setAction($this->url(array('module'=>'content','controller'=>'index','action'=>'search')));
                    echo $searchForm;
                    ?>
                    <br />
                </div>

<?php echo $this->layout()->content; ?>
            </div>
            <div class="clear"></div>

            <div class="grid_16" id="site_info">
                <div class="box">
                    <p>Fluid 960 Grid System, created by <a href="http://www.domain7.com/WhoWeAre/StephenBau.html">Stephen Bau</a>, based on the <a href="http://960.gs/">960 Grid System</a> by <a href="http://sonspring.com/journal/960-grid-system">Nathan Smith</a>. Released under the 
                        <a href="../../../licenses/GPL_license.txt">GPL</a> / <a href="../../../licenses/MIT_license.txt">MIT</a> <a href="../../../README.txt">Licenses</a>.</p>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </body>
</html>
<?php
$this->addScriptPath(APPLICATION_PATH . '/views/scripts');
echo $this->render('profiler.phtml');
?>